services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jellypodbuild
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./data:/app/data
      - /mnt/ipod:/ipod
      - /media/music:/musicdir
    environment:
      - MUSIC_MOUNT=/musicdir
    entrypoint: ["./entrypoint.sh"]