services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jellypodbuild
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./data:/app/data
      - /Volumes/PAULPOD:/ipod
      - ./music3:/musicdir
    environment:
      - MUSIC_MOUNT=/musicdir
      - RESET_IPOD=true
    entrypoint: ["./entrypoint.sh"]